const mongoose = require('mongoose');

const workerInvoiceSchema = new mongoose.Schema({
  invoiceNumber: {
    type: String,
    required: true,
    unique: true
  },
  workerId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  salonId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Salon',
    required: true
  },
  // Invoice period
  periodStart: {
    type: Date,
    required: true
  },
  periodEnd: {
    type: Date,
    required: true
  },
  // Financial details
  totalAmount: {
    type: Number,
    required: true,
    min: 0
  },
  appointmentsCount: {
    type: Number,
    default: 0
  },
  // Breakdown of earnings
  breakdown: [{
    appointmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Appointment'
    },
    serviceName: String,
    servicePrice: Number,
    workerEarning: Number,
    commissionPercentage: Number,
    date: Date
  }],
  // Payment details
  status: {
    type: String,
    enum: ['pending', 'paid', 'cancelled'],
    default: 'pending'
  },
  paidDate: {
    type: Date,
    default: null
  },
  paymentMethod: {
    type: String,
    enum: ['cash', 'bank_transfer', 'check', 'other'],
    default: 'cash'
  },
  notes: {
    type: String,
    default: ''
  },
  // Generated by
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  }
}, {
  timestamps: true
});

// Index for faster queries
workerInvoiceSchema.index({ workerId: 1, salonId: 1, createdAt: -1 });
workerInvoiceSchema.index({ invoiceNumber: 1 });
workerInvoiceSchema.index({ status: 1 });

// Generate unique invoice number
workerInvoiceSchema.statics.generateInvoiceNumber = async function() {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  
  // Count invoices today
  const startOfDay = new Date(date.setHours(0, 0, 0, 0));
  const endOfDay = new Date(date.setHours(23, 59, 59, 999));
  
  const count = await this.countDocuments({
    createdAt: { $gte: startOfDay, $lte: endOfDay }
  });
  
  const sequence = String(count + 1).padStart(4, '0');
  return `INV-${year}${month}${day}-${sequence}`;
};

module.exports = mongoose.model('WorkerInvoice', workerInvoiceSchema);

